### ISSUE TITLE
Написать апи присоединения игрока к игре

### ISSUE THREAD

**Issue by rashemihmih** [akapust1n/Imagination#8]

**Comment by rashemihmih** [comment]
запрос:
`{'type': 'GameJoin', 'content': {'viewer_id': string, 'api_id': string, 'auth_key': string}}`
успех:
`{'type': 'Queue'}`
ошибка авторизации:
`{'type': 'Error', 'content': 'Ошибка авторизации'}`

**Comment by akapust1n** [comment]
**_Api только на английском_**
запрос:
{'type': 'GameJoin', 'content': {'viewer_id': string, 'api_id': string, 'auth_key': string}}
успех:
{'type': 'Queue'}
ошибка авторизации:
{'type': 'Error', 'content': 'AuthError'}

**Comment by rashemihmih** [comment]
**_DEPRECATED_**
Успешный подбор игры:
`{'type': 'MasterTurn', 'content': {'players': [string]}}`

**Comment by rashemihmih** [comment]
Успешный подбор игры:
```
{
    'type': 'MasterTurn', 
    'content': {
        'players': [{
            'viewer_id': string,
            'score': int
        }],
        'hand': [{
            'card_id': string,
            'card_url': string
        }],
        'master': string,
        'deck': int
    }
}
```
master - viewer_id ведущего, deck - число карт в колоде
